# Site settings
name: wwhu668
email: wwhu668@163.com
author: wwhu668
url: 
resume_site: 
github: https://github.com/wwhu668/
baseurl: ""
description: wwhu668 的博客
meta_description: 吴文虎;个人博客;事出反常必有妖
motto: 
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wwhu668
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : 
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
